### ISSUE TITLE
network unusable

### ISSUE THREAD

**Issue by carolynsteeves1** [chashtag/PiCash#10]
✔ Checking prerequisites...
2022-10-27 12:19:58 ✔ Installing...
2022-10-27 12:19:59 ✔ Creating directory /etc/earnapp
2022-10-27 12:19:59 ✔ Fetching earnapp-aarch64-1.331.28
Authorisation successful
ID: 7a19e7246c5a9ef6ddddd69f5519207a51fcf8a1fa8e5148efa80e
Honeygain service is starting
API Error: Network Unusable

.----.

How do i fix this? Im trying to deploy on an arm machine

**Comment by Jonny11bonk** [comment]
If you have obviously checked Honeygain's FAQ page, you would know that only ISP/MOB and COM types are supported. DCH and other usage types are unusable.
