### ISSUE TITLE
Storage gets fully filled up

### ISSUE THREAD

**Issue by uwuclxdy** [chashtag/PiCash#12]
Using only honeygain, it fills up the storage completely after a while. After uninstalling its folder (/var/lib/docker/overlay2/da57c9f21e2dcac19a8c5ab39a6d56ed054c3c25cd6c8537e5bc88f1f4862cfc) is all fine.

![image](https://user-images.githubusercontent.com/37777261/215355514-3382bcc0-20ee-4e75-8970-899949cb67ed.png)
![image](https://user-images.githubusercontent.com/37777261/215355526-bcf5900e-b0c4-4a97-af79-f9195b5ab925.png)

**Comment by chashtag** [comment]
A new container has been built with log rotation
