### ISSUE TITLE
Error: No such container: picash

### ISSUE THREAD

**Issue by gabltz** [chashtag/PiCash#4]
> `sudo bash run.sh
Unable to find image 'chashtag/picash:latest' locally
latest: Pulling from chashtag/picash 
docker: no matching manifest for linux/arm/v7 in the manifest list entries
See 'docker run --help'. 
Waiting for 30 sec to stand up, will print the earnapp link when done
Use this link to register your worker Error: No such container: picash `

anyfix ?

**Comment by chashtag** [comment]
Hello,
I dont normally run my Pi's outside of arm64, I have built a 32bit(armhf) container If you would be kind enough to test it out.

`docker run --restart unless-stopped --env-file settings.conf --name picash chashtag/picash:test`

**Comment by rbalonek** [comment]
Hi, having the same issue.  tried the above and getting:  Restarting (139) x seconds ago on a loop.

**Comment by chashtag** [comment]
An arm7 container has been built with the latest tag

**Comment by rbalonek** [comment]
Hey, I tried 
`docker run --restart unless-stopped --env-file settings.conf --name picash chashtag/picash:latest`

as well as 
`docker run --restart unless-stopped --env-file settings.conf --name picash chashtag/picash:test`

but I'm still getting 
"WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested"

And then getting the lopped restart. 

Pawns runs using their own docker directions, but when I tried to only use that in settings.conf, I am still getting looping through restarts. Raspberri Pi Zero w
