### ISSUE TITLE
Infinite restart Raspberri Pi Zero

### ISSUE THREAD

**Issue by rbalonek** [chashtag/PiCash#8]
Hey, I tried the regular setup, and then:
docker run --restart unless-stopped --env-file settings.conf --name picash chashtag/picash:latest

as well as
docker run --restart unless-stopped --env-file settings.conf --name picash chashtag/picash:test

but I'm still getting
"WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested"

And then getting the lopped restart.

Pawns runs using their own docker directions, but when I tried to only use that in settings.conf, I am still getting looping through restarts. Raspberri Pi Zero w

**Comment by chashtag** [comment]
Currently Pi Zero W are not supported, only the newer Zero 2 W's
I do not have a raspberry pi zero W to build against. I will l look into getting one in the future.
